# -*- coding: utf-8 -*-
"""India Census 2011.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OcTBY-CENpEhK2LAsl7de08KIn4Huk0c
"""

import pandas as pd

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("6. India Census 2011.csv")
df.head()

dfcopy = df.copy()
dfcopy.head()

dfcopy.tail()

dfcopy.shape

dfcopy.dtypes

dfcopy.nunique()

dfcopy.info()

dfcopy.isnull().sum()

"""# 1. How will you hide the indexes of dataframe"""

dfcopy.style.hide_index()

"""# 2. How can we see the heading on the dataframe"""

dfcopy.head(2)

dfcopy.style.set_caption('India Census 2011 Dataset')

"""# 3. Show the records related with the districts - New Delhi, Lucknow, Jaipur"""

dfcopy.columns

dfcopy[dfcopy['District_name'].isin(['New Delhi', 'Lucknow', 'Jaipur'])]

"""# 4. Calculate state-wise :
# A. Total number of population.
# B. Total no. of population with different religions
"""

dfcopy.head(2)

# A. Total number of population.
dfcopy.groupby('State_name').Population.sum().sort_values(ascending = False)

# B. Total no. of population with different religions
dfcopy.columns

dfcopy.groupby('State_name')['Hindus', 'Muslims', 'Christians', 'Sikhs', 'Buddhists', 'Jains'].sum()

"""# 5. How many Male Workers were there in Maharashtra state"""

dfcopy.head(2)

dfcopy[dfcopy.State_name == 'MAHARASHTRA'].sum()
# There are 32616875 male workers in Maharashtra

dfcopy[dfcopy.State_name == 'MAHARASHTRA']['Male_Workers'].sum()

"""# 6. How to set a columns as index in the dataframe"""

dfcopy.head(3)

dfcopy.set_index('District_code', inplace = True)

dfcopy.head(2)

"""# 7a) Add a Suffix to the column names
# 7b) Add a Prefix to the column names
"""

dfcopy.head(2)

# add suffix
dfcopy = dfcopy.add_suffix('_rightone')

# add prefix
dfcopy = dfcopy.add_prefix('leftone_')

dfcopy.head(10)